insert into
  "Movies"
values
  (
    uuid_generate_v4(),
    'Fury',
    'A seasoned tank commander leads his crew on a dangerous mission behind enemy lines in the final months of World War II.',
    2014,
    'USA',
    'English',
    7.6,
    134,
    'https://mir-s3-cdn-cf.behance.net/project_modules/hd/40055038000869.5752d5db039c2.jpg',
    'https://ae01.alicdn.com/kf/S479e3f980dac4c048b2bcfa3dcec7e20a.jpg',
    'https://www.youtube.com/watch?v=q94n3eWOWXM',
    false
  ),
  (
    uuid_generate_v4(),
    'The Pacific',
    'A companion series to ''Band of Brothers'', depicting the Pacific Theater of World War II through the experiences of U.S. Marines.',
    2010,
    'USA',
    'English',
    8.3,
    NULL,
    'https://m.media-amazon.com/images/M/MV5BNGFjYTZmYjEtZDI3MS00MGVhLWI5NDQtY2QwZTcwNjUwMTA2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=Q1fXW-dU1Cc',
    false
  ),
  (
    uuid_generate_v4(),
    'Saving Private Ryan',
    'After the Normandy invasion, a group of soldiers goes behind enemy lines to find and bring back Private James Ryan.',
    1998,
    'USA',
    'English',
    8.6,
    169,
    'https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=9CiW_DgxCnQ',
    false
  ),
  (
    uuid_generate_v4(),
    'The Two Popes',
    'Behind Vatican walls, Pope Benedict and the future Pope Francis must find common ground to forge a new path for the Catholic Church.',
    2019,
    'UK, Italy, Argentina, USA',
    'English, Spanish, Latin, Italian, Portuguese, German',
    7.6,
    125,
    'https://www.themoviedb.org/t/p/original/4d4mTSfDIFIbUbMLUfaKodvxYXA.jpg',
    NULL,
    'https://www.youtube.com/watch?v=T5OhkFY1PQE',
    false
  ),
  (
    uuid_generate_v4(),
    'Hacksaw Ridge',
    'The true story of Desmond Doss, a medic who served in WWII without carrying a weapon and saved 75 men during the Battle of Okinawa.',
    2016,
    'USA',
    'English',
    8.1,
    139,
    'https://m.media-amazon.com/images/M/MV5BMjQ1NjM3MTUxNV5BMl5BanBnXkFtZTgwMDc5MTY5OTE@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=s2-1hz1juBI',
    false
  ),
  (
    uuid_generate_v4(),
    'Dunkirk',
    'A visually stunning retelling of the Dunkirk evacuation, told from three perspectives: land, sea, and air.',
    2017,
    'UK, Netherlands, France, USA',
    'English',
    7.8,
    106,
    'https://juicyreviewz.files.wordpress.com/2017/07/dunkirk-movie-poster.jpg',
    NULL,
    'https://www.youtube.com/watch?v=T7O7BtBnsG4',
    false
  ),
  (
    uuid_generate_v4(),
    'Band of Brothers',
    'Follows Easy Company, a unit of the 506th Parachute Infantry Regiment during World War II, from training to the end of the war.',
    2001,
    'USA',
    'English',
    9.4,
    NULL,
    'https://m.media-amazon.com/images/M/MV5BMTQ3NTdmOTEtZTRmMi00NTg5LWI5NmUtYTNiOTc0ZmNkODU0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=KKRBAFlN5ww',
    false
  );

insert into
  "Movies"
values
  (
    uuid_generate_v4(),
    'Schindler''s List',
    'The powerful story of Oskar Schindler, who saved the lives of over a thousand Jewish refugees during the Holocaust.',
    1993,
    'USA',
    'English, Hebrew, German, Polish',
    9.0,
    195,
    'https://th.bing.com/th/id/OIP.IxTgcmpZDCkzFwfGkOXSsQHaLH?rs=1&pid=ImgDetMain',
    NULL,
    'https://www.youtube.com/watch?v=mxphAlJID9U',
    false
  ),
  (
    uuid_generate_v4(),
    'Black Hawk Down',
    'An intense retelling of the 1993 U.S. military mission in Somalia, where soldiers struggle to survive a chaotic battle.',
    2001,
    'USA, UK',
    'English',
    7.7,
    144,
    'https://i.pinimg.com/originals/6b/ad/ca/6badcaa46209fd756b920a4ab4a914a2.jpg',
    NULL,
    'https://www.youtube.com/watch?v=V1UV3Vj4z0w',
    false
  ),
  (
    uuid_generate_v4(),
    'The Thin Red Line',
    'A philosophical and poetic depiction of the Battle of Guadalcanal in World War II.',
    1998,
    'USA',
    'English',
    7.6,
    170,
    'https://m.media-amazon.com/images/M/MV5BMzQ5NmViMDUtMjI1NC00ZWJkLTkwNzctMmIxZWY2MzQyZDc2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=WHHAcqZMlqA',
    false
  ),
  (
    uuid_generate_v4(),
    'The Imitation Game',
    'During World War II, mathematician Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.',
    2014,
    'UK, USA',
    'English',
    8.0,
    113,
    'https://m.media-amazon.com/images/M/MV5BNjI3NjY1Mjg3MV5BMl5BanBnXkFtZTgwMzk5MDQ3MjE@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=j2jRs4EAvWM',
    false
  ),
  (
    uuid_generate_v4(),
    'Darkest Hour',
    'In the early days of World War II, Winston Churchill faces a critical decision as he must choose whether to negotiate with Hitler or fight on against incredible odds.',
    2017,
    'UK',
    'English',
    7.4,
    125,
    'https://thafd.bing.com/th/id/OIP.LXLTrUgUFe3HQH6t-Hu9JQHaLH?rs=1&pid=ImgDetMain',
    NULL,
    'https://www.youtube.com/watch?v=LtJ60u7SUSw',
    false
  ),
  (
    uuid_generate_v4(),
    'American Sniper',
    'Navy SEAL sniper Chris Kyle''s pinpoint accuracy saves lives on the battlefield, but he struggles with life back home.',
    2014,
    'USA',
    'English',
    7.3,
    133,
    'https://m.media-amazon.com/images/M/MV5BMTkxNzI3ODI4Nl5BMl5BanBnXkFtZTgwMjkwMjY4MjE@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=99k3u9ay1gs',
    false
  ),
  (
    uuid_generate_v4(),
    'Letters from Iwo Jima',
    'The story of the Battle of Iwo Jima between the United States and Imperial Japan during World War II, told from the Japanese perspective.',
    2006,
    'Japan, USA',
    'Japanese',
    7.9,
    141,
    'https://m.media-amazon.com/images/M/MV5BMjE0NzgwODI4M15BMl5BanBnXkFtZTcwNjg3OTA0MQ@@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=RarFebAZklw',
    false
  ),
  (
    uuid_generate_v4(),
    'The Pianist',
    'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.',
    2002,
    'France, Germany, Poland, UK',
    'English, German, Russian',
    8.5,
    150,
    'https://m.media-amazon.com/images/M/MV5BMjEwNmEwYjgtNTk3ZC00NjljLTg5ZDctZTY3ZGQwZjRkZmQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=rLgGA6XA7pY',
    false
  ),
  (
    uuid_generate_v4(),
    'Braveheart',
    'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.',
    1995,
    'USA',
    'English, Scots, Latin',
    8.3,
    178,
    'https://m.media-amazon.com/images/M/MV5BNGMxZDBhNGQtYTZlNi00N2UzLWI4NDEtNmUzNWM2NTdmZDA0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=sDjFWzPjXbg',
    false
  ),
  (
    uuid_generate_v4(),
    'Platoon',
    'A young soldier in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man.',
    1986,
    'USA',
    'English',
    8.1,
    120,
    'https://m.media-amazon.com/images/M/MV5BNDViODhmNjEtNWQ2Zi00MDdjLWIzMjAtODA4NjI1Y2I0YmIzXkEyXkFqcGc@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=R8weLPF4qBQ',
    false
  ),
  (
    uuid_generate_v4(),
    'Patton',
    'The story of General George S. Patton''s career during World War II and his controversial leadership style.',
    1970,
    'USA',
    'English, German',
    8.0,
    172,
    'https://m.media-amazon.com/images/M/MV5BYzQwNmI5MDItMGEyZi00Y2FjLTkzMTUtOTliOTIyOWRlN2Q0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=bJktjxB6fhI',
    false
  ),
  (
    uuid_generate_v4(),
    'Outlaw King',
    'A true David vs. Goliath story of how the 14th-century Scottish ''Outlaw King'' Robert the Bruce used cunning and bravery to defeat the much larger and better-equipped occupying English army.',
    2018,
    'UK, USA',
    'English',
    6.9,
    121,
    'https://m.media-amazon.com/images/M/MV5BZjI0MGZkYjItODFmZC00OWIyLTk4MDctYTIwZDZhYThhYWNlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=Q-G1BME8FKw',
    false
  ),
  (
    uuid_generate_v4(),
    'Enemy at the Gates',
    'A Russian sniper and a German sniper play a deadly game of cat-and-mouse during the Battle of Stalingrad.',
    2001,
    'France, Germany, UK, Ireland, USA',
    'English, German, Russian',
    7.6,
    131,
    'https://m.media-amazon.com/images/M/MV5BODM5MmQyYjktMzg5Ny00Y2Y1LThlNWQtNjQ5OGMwNmY2YjcyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=UG25omjpoOI',
    false
  ),
(
    uuid_generate_v4(),
    'The Longest Day',
    'The events of D-Day, told on a grand scale from both the Allied and German points of view.',
    1962,
    'USA',
    'English, German, French',
    7.7,
    178,
    'https://m.media-amazon.com/images/M/MV5BYmM0NjAzZWUtMGZmYi00Nzc4LTk4Y2YtOWQ1NmE4ZTlkOTFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=upOko4gW2GE',
    false
),
(
    uuid_generate_v4(),
    'Beasts of No Nation',
    'A young boy in an unnamed African country is forced to join a group of rebel fighters.',
    2015,
    'USA',
    'English',
    7.7,
    137,
    'https://m.media-amazon.com/images/M/MV5BMTYwMzMzMDI0NF5BMl5BanBnXkFtZTgwNDQ3NjI3NjE@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=2xb9Ty-1frw',
    false
),
(
    uuid_generate_v4(),
    '1917',
    'During World War I, two British soldiers are given an urgent mission to deliver a message that could save 1,600 men.',
    2019,
    'UK, USA',
    'English',
    8.2,
    119,
    'https://m.media-amazon.com/images/M/MV5BYzkxZjg2NDQtMGVjMy00NWZkLTk0ZDEtZWE3NDYwYjAyMTg1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=YqNYrYUiMfg',
    false
),
(
    uuid_generate_v4(),
    'Come and See',
    'A boy joins Soviet partisans during WWII and experiences the horror of war.',
    1985,
    'Soviet Union',
    'Russian, Belarusian, German',
    8.4,
    142,
    'https://m.media-amazon.com/images/M/MV5BNDlkZmVkZDAtZGFmMS00OWIzLWJkY2YtNWE5NjNhNjhiZGE3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=BcCbX1fqFKA',
    false
),
(
    uuid_generate_v4(),
    'The Godfather',
    'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    1972,
    'USA',
    'English, Italian',
    9.2,
    175,
    'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=UaVTIH8mujA',
    false
),
(
    uuid_generate_v4(),
    'Stalingrad',
    'German soldiers endure the siege of Stalingrad during one of the war''s bloodiest battles.',
    1993,
    'Germany',
    'German, Russian',
    7.5,
    134,
    'https://m.media-amazon.com/images/M/MV5BODRiMjFkMmItY2IxZC00YWJmLWJlZTAtMDNhNzY0YmRiMmY4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=k_i7UEQcg_0',
    false
),
(
    uuid_generate_v4(),
    'The Dark Knight',
    'When the menace known as the Joker wreaks havoc and chaos on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    2008,
    'USA, UK',
    'English',
    9.0,
    152,
    'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    false
),
(
    uuid_generate_v4(),
    'Kajaki',
    'A harrowing tale of survival when a British patrol in Afghanistan triggers a landmine.',
    2014,
    'UK',
    'English',
    7.1,
    108,
    'https://m.media-amazon.com/images/M/MV5BMTQ5MjYxMDM4MV5BMl5BanBnXkFtZTgwNDU2NzA0MzE@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=D5vhurFXu5c',
    false
),
(
    uuid_generate_v4(),
    'The Shape of Water',
    'In a 1960s research facility, a mute janitor forms a unique relationship with an amphibious creature held in captivity.',
    2017,
    'USA',
    'English',
    7.3,
    123,
    'https://m.media-amazon.com/images/M/MV5BOGFlMTM2MTgtZDdlMy00ZDZlLWFjOTUtZDMzMGEwNmNiMWY0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=XFYWazblaUA',
    false
),
(
    uuid_generate_v4(),
    'The Painted Bird',
    'A young boy wanders through Eastern Europe during WWII encountering brutality and horror.',
    2019,
    'Czech Republic, Ukraine, Slovakia',
    'Interslavic',
    7.0,
    169,
    'https://m.media-amazon.com/images/M/MV5BOGE0YjI3MjEtY2I2Yy00ODIyLTg1MmYtYzA2ZGU2MGYyZTc5XkEyXkFqcGc@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=bRDuc3IdOn8',
    false
),
(
    uuid_generate_v4(),
    'The Flowers of War',
    'A Westerner shelters a group of women during the 1937 Nanking Massacre.',
    2011,
    'China',
    'Mandarin, English',
    7.5,
    146,
    'https://m.media-amazon.com/images/M/MV5BMjE3OTUzODA3Ml5BMl5BanBnXkFtZTcwNDk5NTUyNw@@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=cj2uhyfVNmQ',
    false
),
(
    uuid_generate_v4(),
    'The Siege of Jadotville',
    'Irish soldiers under UN command fight off a siege during a 1961 Congo crisis.',
    2016,
    'Ireland',
    'English',
    7.2,
    108,
    'https://m.media-amazon.com/images/M/MV5BNjJhZGY0NTUtOTI0Yi00NGY5LTk4ZWYtYmVmNGFiMTZiZTgwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=9_JHsiQTTmg',
    false
),
(
    uuid_generate_v4(),
    'Joker',
    'In Gotham City, a mentally troubled comedian embarks on a downward spiral that leads to the creation of an iconic villain.',
    2019,
    'USA',
    'English',
    8.4,
    122,
    'https://m.media-amazon.com/images/M/MV5BNzY3OWQ5NDktNWQ2OC00ZjdlLThkMmItMDhhNDk3NTFiZGU4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=zAGVQLHvwOY',
    false
),
(
    uuid_generate_v4(),
    'Napoleon',
    'An epic portrayal of Napoleon Bonaparte''s rise to power, his military triumphs, and his complex relationship with Empress Joséphine.',
    2023,
    'USA',
    'English',
    6.5,
    158,
    'https://m.media-amazon.com/images/M/MV5BM2ZiZjRkZDYtOTA5Ny00YjZhLWJkMzctNGU5NmI2NGMyYzE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=OAZWXUkrjPc',
    false
),
(
    uuid_generate_v4(),
    'The Outpost',
    'US soldiers defend a remote base from Taliban forces in Afghanistan.',
    2020,
    'USA',
    'English',
    6.8,
    123,
    'https://m.media-amazon.com/images/M/MV5BNTQyZDhkYWYtMDE3YS00NWEyLWI1YWYtOTg4YzM5MTM1YTE0XkEyXkFqcGc@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=f4LM9a02q9Q',
    false
),
(
    uuid_generate_v4(),
    'Grown Ups',
    'After their high school basketball coach passes away, five friends reunite for a Fourth of July holiday weekend.',
    2010,
    'USA',
    'English',
    5.9,
    102,
    'https://m.media-amazon.com/images/M/MV5BMjA0ODYwNzU5Nl5BMl5BanBnXkFtZTcwNTI1MTgxMw@@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=e01NVCveGkg',
    false
),
(
    uuid_generate_v4(),
    'In This Corner of the World',
    'A young woman in Hiroshima tries to survive the hardships of World War II.',
    2016,
    'Japan',
    'Japanese',
    7.8,
    129,
    'https://m.media-amazon.com/images/M/MV5BMjk2MjViY2QtNjZjZS00OTI5LWI1NmQtNmZiZDEyYjIxMGMwXkEyXkFqcGc@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=-jBe-uHhlNs',
    false
),
(
    uuid_generate_v4(),
    'Battle for Sevastopol',
    'The story of female sniper Lyudmila Pavlichenko in WWII.',
    2015,
    'Russia, Ukraine',
    'Russian, English',
    7.1,
    110,
    'https://m.media-amazon.com/images/M/MV5BNDRjYjcxNWMtMTIxYi00MDJhLWFhY2YtN2RmZjNhZDNiNTFhXkEyXkFqcGc@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=DrbRyxCWLx0',
    false
),
(
    uuid_generate_v4(),
    'Django Unchained',
    'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
    2012,
    'USA',
    'English, German, French',
    8.5,
    165,
    'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=_iH0UBYDI4g',
    false
),
(
    uuid_generate_v4(),
    'The Shawshank Redemption',
    'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
    1994,
    'USA',
    'English',
    9.3,
    140,
    'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=PLl99DlL6b4',
    false
),
(
    uuid_generate_v4(),
    'A Minecraft Movie',
    'Four misfits are suddenly pulled through a mysterious portal into a bizarre cubic wonderland that thrives on imagination. To get back home they''ll have to master this world while embarking on a quest with an unexpected expert crafter.',
    2025,
    'USA',
    'English',
    5.9,
    101,
    'https://thafd.bing.com/th?id=OIF.V4r7tFs5zXdj3Lv%2fM8gZfw&rs=1&pid=ImgDetMain',
    NULL,
    'https://www.youtube.com/watch?v=wJO_vIDZn-I&t=11s',
    false
),
(
    uuid_generate_v4(),
    'Generation Kill',
    'A mini-series based on Rolling Stone reporter Evan Wright''s experiences with the 1st Reconnaissance Battalion during the 2003 Iraq invasion.',
    2008,
    'USA',
    'English',
    8.5,
    7,
    'https://m.media-amazon.com/images/M/MV5BMTM2NjAxOTQzNl5BMl5BanBnXkFtZTcwMjk4NzU3MQ@@._V1_FMjpg_UX1000_.jpg',
    NULL,
    'https://www.youtube.com/watch?v=vZwRpmSViHU',
    false
);

select
  *
from
  "Movies"